service: homepage
runtime: nodejs14
handlers:
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    secure: always
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
